Move to gawk-3.1.6.

diff --git a/test/Makefile.am b/test/Makefile.am
--- a/test/Makefile.am
+++ b/test/Makefile.am
@@ -1,14 +1,14 @@
 #
 # test/Makefile.am --- automake input file for gawk
 #
-# Copyright (C) 1988-2005 the Free Software Foundation, Inc.
+# Copyright (C) 1988-2006 the Free Software Foundation, Inc.
 #
 # This file is part of GAWK, the GNU implementation of the
 # AWK Programming Language.
 #
 # GAWK is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2 of the License, or
+# the Free Software Foundation; either version 3 of the License, or
 # (at your option) any later version.
 #
 # GAWK is distributed in the hope that it will be useful,
@@ -99,6 +99,7 @@ EXTRA_DIST = \
 	backw.in \
 	backw.ok \
 	badargs.ok \
+	binmode1.ok \
 	childin.awk \
 	childin.in \
 	childin.ok \
@@ -121,6 +122,9 @@ EXTRA_DIST = \
 	concat2.ok \
 	concat3.awk \
 	concat3.ok \
+	concat4.awk \
+	concat4.in \
+	concat4.ok \
 	convfmt.awk \
 	convfmt.ok \
 	datanonl.awk \
@@ -134,6 +138,18 @@ EXTRA_DIST = \
 	delarpm2.ok \
 	delfunc.awk \
 	delfunc.ok \
+	devfd.in1 \
+	devfd.in2 \
+	devfd.in4 \
+	devfd.in5 \
+	devfd.ok \
+	devfd1.awk \
+	devfd1.ok \
+	devfd2.ok \
+	double1.awk \
+	double1.ok \
+	double2.awk \
+	double2.ok \
 	dynlj.awk \
 	dynlj.ok \
 	eofsplit.awk \
@@ -142,6 +158,7 @@ EXTRA_DIST = \
 	exitval1.ok \
 	exitval2.awk \
 	exitval2.ok \
+	exitval2.w32 \
 	fflush.ok \
 	fflush.sh \
 	fieldwdth.awk \
@@ -153,6 +170,8 @@ EXTRA_DIST = \
 	fldchgnf.awk \
 	fldchgnf.in \
 	fldchgnf.ok \
+	fmtspcl.awk \
+	fmtspcl.tok \
 	fmttest.awk \
 	fmttest.ok \
 	fnamedat.awk \
@@ -199,6 +218,12 @@ EXTRA_DIST = \
 	funstack.awk \
 	funstack.in \
 	funstack.ok \
+	fwtest.awk \
+	fwtest.in \
+	fwtest.ok \
+	fwtest2.awk \
+	fwtest2.in \
+	fwtest2.ok \
 	gensub.awk \
 	gensub.in \
 	gensub.ok \
@@ -269,6 +294,8 @@ EXTRA_DIST = \
 	inputred.ok \
 	intest.awk \
 	intest.ok \
+	intformat.awk \
+	intformat.ok \
 	intprec.awk \
 	intprec.ok \
 	iobug1.awk \
@@ -280,8 +307,13 @@ EXTRA_DIST = \
 	leadnl.ok \
 	lint.awk \
 	lint.ok \
+	lintold.awk \
+	lintold.in \
+	lintold.ok \
 	litoct.awk \
 	litoct.ok \
+	localenl.ok \
+	localenl.sh \
 	longdbl.awk \
 	longdbl.in \
 	longdbl.ok \
@@ -308,7 +340,11 @@ EXTRA_DIST = \
 	messages.awk \
 	minusstr.awk \
 	minusstr.ok \
+	mixed1.ok \
 	mmap8k.in \
+	mtchi18n.awk \
+	mtchi18n.in \
+	mtchi18n.ok \
 	nasty.awk \
 	nasty.ok \
 	nasty2.awk \
@@ -336,6 +372,7 @@ EXTRA_DIST = \
 	nlstrina.ok \
 	noeffect.awk \
 	noeffect.ok \
+	nofile.ok \
 	nofmtch.awk \
 	nofmtch.ok \
 	noloop1.awk \
@@ -387,10 +424,18 @@ EXTRA_DIST = \
 	out1.ok \
 	out2.ok \
 	out3.ok \
+	ovrflow1.awk \
+	ovrflow1.ok \
 	paramdup.awk \
 	paramdup.ok \
 	paramtyp.awk \
 	paramtyp.ok \
+	parse1.awk \
+	parse1.in \
+	parse1.ok \
+	parsefld.awk \
+	parsefld.in \
+	parsefld.ok \
 	parseme.awk \
 	parseme.ok \
 	pcntplus.awk \
@@ -456,6 +501,9 @@ EXTRA_DIST = \
 	reint.awk \
 	reint.in \
 	reint.ok \
+	reint2.awk \
+	reint2.in \
+	reint2.ok \
 	reparse.awk \
 	reparse.in \
 	reparse.ok \
@@ -525,6 +573,8 @@ EXTRA_DIST = \
 	strtod.awk \
 	strtod.in \
 	strtod.ok \
+	strnum1.awk \
+	strnum1.ok \
 	strtonum.awk \
 	strtonum.ok \
 	strftime.awk \
@@ -533,6 +583,8 @@ EXTRA_DIST = \
 	subamp.awk \
 	subamp.in \
 	subamp.ok \
+	subi18n.awk \
+	subi18n.ok \
 	subsepnm.awk \
 	subsepnm.ok \
 	subslash.awk \
@@ -545,6 +597,8 @@ EXTRA_DIST = \
 	switch2.awk \
 	synerr1.awk \
 	synerr1.ok \
+	synerr2.awk \
+	synerr2.ok \
 	tradanch.awk \
 	tradanch.in \
 	tradanch.ok \
@@ -564,9 +618,25 @@ EXTRA_DIST = \
 	whiny.awk \
 	whiny.in \
 	whiny.ok \
+	wideidx.awk \
+	wideidx.in \
+	wideidx.ok \
+	wideidx2.awk \
+	wideidx2.ok \
+	widesub.awk \
+	widesub.ok \
+	widesub2.awk \
+	widesub2.ok \
+	widesub3.awk \
+	widesub3.in \
+	widesub3.ok \
+	widesub4.awk \
+	widesub4.ok \
 	wjposer1.awk \
 	wjposer1.in \
 	wjposer1.ok \
+	zero2.awk \
+	zero2.ok \
 	zeroe0.awk \
 	zeroe0.ok \
 	zeroflag.awk \
@@ -574,48 +644,55 @@ EXTRA_DIST = \
 
 TESTS_WE_ARE_NOT_DOING_YET_FIXME_ONE_DAY = longdbl
 
-# Get rid of core files when cleaning
-CLEANFILES = core core.*
+# Get rid of core files when cleaning and generated .ok file
+CLEANFILES = core core.* fmtspcl.ok
 
 # try to keep these sorted
 BASIC_TESTS = addcomma anchgsub argarray arrayparm arrayref arrymem1 \
 	arrayprm2 arrayprm3 arryref2 arryref3 arryref4 arryref5 arynasty \
 	arynocls aryprm1 aryprm2 aryprm3 aryprm4 aryprm5 aryprm6 aryprm7 \
 	aryprm8 arysubnm asgext awkpath back89 backgsub childin clobber \
-	clsflnam compare compare2 concat1 concat2 concat3 convfmt datanonl defref \
-	delarprm delarpm2 delfunc dynlj eofsplit exitval1 exitval2 fldchg fldchgnf fmttest fnamedat \
+	clsflnam compare compare2 concat1 concat2 concat3 concat4 convfmt datanonl defref \
+	delarprm delarpm2 delfunc dynlj eofsplit exitval1 exitval2 fldchg fldchgnf fmtspcl fmttest fnamedat \
 	fnarray fnarray2 fnarydel fnaryscl fnasgnm fnmisc fnparydl \
 	fordel forsimp fsbs fsspcoln fsrs fstabplus funsemnl funsmnam funstack getline \
 	getline2 getline3 getlnbuf getnr2tb getnr2tm gsubasgn gsubtest \
-	gsubtst2 gsubtst3 gsubtst4 gsubtst5 hex hsprint inputred intest \
+	gsubtst2 gsubtst3 gsubtst4 gsubtst5 hex hsprint inputred intest intformat \
 	intprec iobug1 leaddig leadnl litoct longsub longwrds manglprm math membug1 \
-	messages minusstr mmap8k nasty nasty2 negexp nested nfldstr \
-	nfneg nfset nlfldsep nlinstr nlstrina noeffect nofmtch noloop1 \
+	messages minusstr mmap8k mtchi18n nasty nasty2 negexp nested nfldstr \
+	nfneg nfset nlfldsep nlinstr nlstrina noeffect nofile nofmtch noloop1 \
 	noloop2 nonl noparms nors nulrsend numindex numsubstr octsub ofmt \
-	ofmtbig ofmtfidl ofmts onlynl opasnidx opasnslf paramdup paramtyp \
-	parseme pcntplus prdupval prec printf0 printf1 prmarscl prmreuse \
+	ofmtbig ofmtfidl ofmts onlynl opasnidx opasnslf ovrflow1 paramdup paramtyp \
+	parse1 parsefld parseme pcntplus prdupval prec printf0 printf1 prmarscl prmreuse \
 	prt1eval prtoeval psx96sub rand rebt8b1 rebt8b2 redfilnm regeq \
 	reindops reparse resplit rs rsnul1nl rsnulbig rsnulbig2 rstest1 \
 	rstest2 rstest3 rstest4 rstest5 rswhite scalar sclforin sclifin \
 	sortempty splitargv splitarr splitdef splitvar splitwht sprintfc \
-	strcat1 strtod subamp subsepnm subslash substr swaplns synerr1 tradanch \
-	tweakfld uninit2 uninit3 uninit4 uninitialized unterm wjposer1 \
-	zeroe0 zeroflag
+	strcat1 strtod strnum1 subamp subi18n subsepnm subslash substr swaplns \
+	synerr1 synerr2 tradanch \
+	tweakfld uninit2 uninit3 uninit4 uninitialized unterm wideidx wideidx2 \
+	widesub widesub2 widesub3 widesub4 wjposer1 zeroe0 zeroflag zero2
 
-UNIX_TESTS = fflush getlnhd pid pipeio1 pipeio2 poundbang space strftlng
+UNIX_TESTS = fflush getlnhd localenl pid pipeio1 pipeio2 poundbang space strftlng
 
-GAWK_EXT_TESTS = argtest asort asorti backw badargs clos1way fieldwdth fsfwfs \
-	gensub gensub2 gnuops2 gnuops3 gnureops icasefs icasers igncdym igncfs ignrcase \
-	ignrcas2 lint match1 match2 manyfiles nondec nondec2 posix procinfs \
-	printfbad1 regx8bit rebuf reint rsstart1 rsstart2 rsstart3 \
-	rstest6 shadow sort1 strtonum strftime whiny
+GAWK_EXT_TESTS = argtest asort asorti backw badargs binmode1 clos1way devfd devfd1 devfd2 double1 double2 \
+	fieldwdth fsfwfs fwtest fwtest2 gensub gensub2 gnuops2 gnuops3 gnureops icasefs \
+	icasers igncdym igncfs ignrcase ignrcas2 lint lintold match1 match2 manyfiles \
+	nondec nondec2 posix procinfs printfbad1 regx8bit rebuf reint reint2 rsstart1 \
+	rsstart2 rsstart3 rstest6 shadow sort1 strtonum strftime whiny
 
 EXTRA_TESTS = regtest inftest
 
 INET_TESTS = inetechu inetecht inetdayu inetdayt
 
 # List of the tests which should be run with --lint option:
-NEED_LINT = defref noeffect nofmtch shadow uninit2 uninit3 uninit4 uninitialized
+NEED_LINT = defref fmtspcl noeffect nofmtch shadow uninit2 uninit3 uninit4 uninitialized
+
+# List of the tests which should be run with --lint-old option:
+NEED_LINT_OLD = lintold
+
+# List of the tests which fail with EXIT CODE 1
+FAIL_CODE1 = fnarray2 fnmisc gsubasgn mixed1 noparms paramdup synerr1 synerr2 unterm
 
 # List of the files that appear in manual tests or are for reserve testing:
 GENTESTS_UNUSED = Makefile.in gtlnbufv.awk printfloat.awk switch2.awk
@@ -719,7 +796,7 @@ regtest::
 	@echo 'Some of the output from regtest is very system specific, do not'
 	@echo 'be distressed if your output differs from that distributed.'
 	@echo 'Manual inspection is called for.'
-	AWK=`pwd`/$(AWK) $(srcdir)/regtest.sh
+	AWK=$(AWKPROG) $(srcdir)/regtest.sh
 
 manyfiles::
 	@echo manyfiles
@@ -780,6 +857,11 @@ litoct::
 	@echo ab | $(AWK) --traditional -f $(srcdir)/litoct.awk >_$@
 	@-$(CMP) $(srcdir)/litoct.ok _$@ && rm -f _$@
 
+devfd::
+	@echo $@
+	@$(AWK) 1 /dev/fd/4 /dev/fd/5 4<$(srcdir)/devfd.in4 5<$(srcdir)/devfd.in5 >_$@ 2>&1 || echo EXIT CODE: $$? >> _$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
 fflush::
 	@echo $@
 	@$(srcdir)/fflush.sh >_$@
@@ -806,7 +888,7 @@ tradanch::
 pid::
 	@echo pid
 	@AWKPATH=$(srcdir) AWK=$(AWKPROG) $(SHELL) $(srcdir)/pid.sh $$$$ > _`basename $@` ; :
-	@-$(CMP) $(srcdir)/pid.ok _`basename $@` && rm -f _`basename $@` _`basename $@`.in
+	@-$(CMP) $(srcdir)/pid.ok _`basename $@` && rm -f _`basename $@`
 
 strftlng::
 	@echo $@
@@ -820,6 +902,14 @@ nors::
 	@echo $@
 	@echo A B C D E | tr -d '\12\15' | $(AWK) '{ print $$NF }' - $(srcdir)/nors.in > _$@
 	@-$(CMP) $(srcdir)/nors.ok _$@ && rm -f _$@
+
+fmtspcl.ok: fmtspcl.tok Makefile
+	@$(AWK) -v "sd=$(srcdir)" 'BEGIN {pnan = sprintf("%g",sqrt(-1)); nnan = sprintf("%g",-sqrt(-1)); pinf = sprintf("%g",-log(0)); ninf = sprintf("%g",log(0))} {sub(/positive_nan/,pnan); sub(/negative_nan/,nnan); sub(/positive_infinity/,pinf); sub(/negative_infinity/,ninf); sub(/fmtspcl/,(sd"/fmtspcl")); print}' < $(srcdir)/fmtspcl.tok > $@ 2>/dev/null
+
+fmtspcl: fmtspcl.ok
+	@echo fmtspcl
+	@$(AWK) -f $(srcdir)/fmtspcl.awk  --lint >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $@.ok _$@ && rm -f _$@
 
 reint::
 	@echo $@
@@ -923,6 +1013,42 @@ whiny::
 	@WHINY_USERS=1 $(AWK) -f $(srcdir)/$@.awk $(srcdir)/$@.in >_$@
 	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
 
+wideidx::
+	@echo $@
+	@[ -z "$$GAWKLOCALE" ] && GAWKLOCALE=en_US.UTF-8; \
+	AWKPATH=$(srcdir) $(AWK) -f $@.awk  < $(srcdir)/$@.in >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+wideidx2::
+	@echo $@
+	@[ -z "$$GAWKLOCALE" ] && GAWKLOCALE=en_US.UTF-8; \
+	AWKPATH=$(srcdir) $(AWK) -f $@.awk >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+widesub::
+	@echo $@
+	@[ -z "$$GAWKLOCALE" ] && GAWKLOCALE=en_US.UTF-8; \
+	AWKPATH=$(srcdir) $(AWK) -f $@.awk  >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+widesub2::
+	@echo $@
+	@[ -z "$$GAWKLOCALE" ] && GAWKLOCALE=en_US.UTF-8; \
+	AWKPATH=$(srcdir) $(AWK) -f $@.awk  >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+widesub3::
+	@echo $@
+	@[ -z "$$GAWKLOCALE" ] && GAWKLOCALE=en_US.UTF-8; \
+	AWKPATH=$(srcdir) $(AWK) -f $@.awk  < $(srcdir)/$@.in >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+widesub4::
+	@echo $@
+	@[ -z "$$GAWKLOCALE" ] && GAWKLOCALE=en_US.UTF-8; \
+	AWKPATH=$(srcdir) $(AWK) -f $@.awk >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
 ignrcas2::
 	@echo $@
 	@GAWKLOCALE=en_US ; export GAWKLOCALE ; \
@@ -967,14 +1093,70 @@ nondec2::
 	@$(AWK) --non-decimal-data -v a=0x1 -f $(srcdir)/$@.awk >_$@
 	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
 
+nofile::
+	@echo $@
+	@$(AWK) '{}' no/such/file >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+binmode1::
+	@echo $@
+	@$(AWK) -v BINMODE=3 'BEGIN { print BINMODE }' >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+subi18n::
+	@echo $@
+	@GAWKLOCALE=en_US.UTF-8 ; $(AWK) -f $(srcdir)/$@.awk > _$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+concat4::
+	@echo $@
+	@GAWKLOCALE=en_US.UTF-8 ; $(AWK) -f $(srcdir)/$@.awk $(srcdir)/$@.in > _$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+devfd1::
+	@echo $@
+	@$(AWK) -f $(srcdir)/$@.awk 4< $(srcdir)/devfd.in1 5< $(srcdir)/devfd.in2 >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+# The program text is the '1' which will print each record. How compact can you get?
+devfd2::
+	@echo $@
+	@$(AWK) 1 /dev/fd/4 /dev/fd/5 4< $(srcdir)/devfd.in1 5< $(srcdir)/devfd.in2 >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+mixed1::
+	@echo $@
+	@$(AWK) -f /dev/null --source 'BEGIN {return junk}' >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+mtchi18n::
+	@echo $@
+	@GAWKLOCALE=ru_RU.UTF-8 ; export GAWKLOCALE ; \
+	$(AWK) -f $(srcdir)/$@.awk $(srcdir)/$@.in >_$@ 2>&1 || echo EXIT CODE: $$? >> _$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+reint2::
+	@echo $@
+	@[ -z "$$GAWKLOCALE" ] && GAWKLOCALE=en_US.UTF-8; \
+	AWKPATH=$(srcdir) $(AWK) --re-interval -f $@.awk $(srcdir)/$@.in >_$@ 2>&1 || echo EXIT CODE: $$? >>_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+localenl::
+	@echo $@
+	@$(srcdir)/$@.sh >_$@
+	@-$(CMP) $(srcdir)/$@.ok _$@ && rm -f _$@
+
+
+
 # Targets generated for other tests:
 include Maketests
 
 $(srcdir)/Maketests: $(srcdir)/Makefile.am $(srcdir)/Gentests
-	$(AWK) -f $(srcdir)/Gentests "$(srcdir)/Makefile.am" *.awk *.in > $(srcdir)/Maketests
+	files=`cd "$(srcdir)" && echo *.awk *.in`; \
+	$(AWK) -f $(srcdir)/Gentests "$(srcdir)/Makefile.am" $$files > $(srcdir)/Maketests
 
 clean:
-	rm -fr _* core core.* junk out1 out2 out3 strftime.ok test1 test2 seq *~
+	rm -fr _* core core.* fmtspcl.ok junk out1 out2 out3 strftime.ok test1 test2 seq *~
 
 # An attempt to print something that can be grepped for in build logs
 pass-fail:
@@ -988,9 +1170,30 @@ pass-fail:
 diffout:
 	for i in _* ; \
 	do  \
+		if [ "$$i" != "_*" ]; then \
 		echo ============== $$i ============= ; \
+		if [ -r $${i#_}.ok ]; then \
+		diff -c $${i#_}.ok $$i ; \
+		else \
 		diff -c $(srcdir)/$${i#_}.ok  $$i ; \
+		fi ; \
+		fi ; \
 	done | more
+
+# convenient way to scan valgrind results for errors
+valgrind-scan:
+	@echo "Scanning valgrind log files for problems:"
+	@$(AWK) '\
+	function show() {if (cmd) {printf "%s: %s\n",FILENAME,cmd; cmd = ""}; \
+	  printf "\t%s\n",$$0}; \
+	{$$1 = ""}; \
+	/Prog and args are:/ {incmd = 1; cmd = ""; next}; \
+	incmd {if (NF == 1) incmd = 0; else {cmd = (cmd $$0); next}}; \
+	/ERROR SUMMARY:/ && !/: 0 errors from 0 contexts/ {show()}; \
+	/definitely lost:/ && !/: 0 bytes in 0 blocks/ {show()}; \
+	/possibly lost:/ && !/: 0 bytes in 0 blocks/ {show()}; \
+	/ suppressed:/ && !/: 0 bytes in 0 blocks/ {show()}; \
+	' log.[0-9]*
 
 # This target is for testing with electric fence.
 efence:
